### ISSUE TITLE
Support multiple projects and wikis

### ISSUE THREAD

**Issue by ppiwow-apay** [arhill05/backstage-plugin-search-backend-module-azure-devops-wiki#1]
Hi,

In the current solution, only one wiki might be configured. Do you plan to support multiple Azure DevOps Projects and wikis?

**Comment by arhill05** [comment]
Hey there @ppiwow-apay! Apologies for not getting back to you quickly. Version 0.5.0 of this package should now support multiple wikis. The documentation in the README has been updated to reflect the change.

Thanks for the suggestion, and please open another issue if you run into problems!
