### ISSUE TITLE
Migrate to New Backend System

### ISSUE THREAD

**Issue by jrtaylorJH** [arhill05/backstage-plugin-search-backend-module-azure-devops-wiki#5]
Hey there, not sure if this plugin is dead such that it would be pointless to make the contribution myself, but I just wanted to record the desire to move this plugin over to be compatible with the new Backend.

https://github.com/backstage/backstage/issues/18301

**Comment by jrtaylorJH** [comment]
@arhill05 If I was to work on this, would it get approved?

**Comment by arhill05** [comment]
Hey @jrtaylorJH! Sorry for the late response. I have fully intended to work on this for this plugin and a few others that I own, but work has had us working hard on core project work and I haven't had the spare time to do it.

If you would like to make a PR, I'll happily approve it.

**Comment by arhill05** [comment]
Hello again @jrtaylorJH! I've published v1.0.1 that migrates to the new backend system, and the README has been updated with proper instructions.

Thanks for raising this issue!

**Comment by jrtaylorJH** [comment]
Thank you! I will look at the PR to learn a bit
